### ISSUE TITLE
Wrong output file name from Munge Step mapped to input file name in Score Step

### ISSUE THREAD

**Issue by davidgormley** [BillmanH/learn-azureml#4]
Hi Bill, After updating line 25 on score_step.py from file name "iris_gold.csv" to "gold_data.csv", I was able to fully run the entire project. Here is the line of code to be pasted in on line 25 of score_step.py:
`inputpath = os.path.join(args.iris_gold, "gold_data.csv")`

**Comment by dataders** [comment]
@davidgormley perfect opportunity to contribute your first open source PR! you can do it from in the browser entirely.
1. Browse to https://github.com/BillmanH/learn-azureml/blob/main/pipes/score_step/score_step.py
2. Click the edit button
    <img width="250" alt="image" src="https://user-images.githubusercontent.com/8158673/101086518-cea7bb00-3565-11eb-944a-a6fa46af8508.png">
3. make the change on line 25.
4. Fill out the info at the bottom
    <img width="695" alt="image" src="https://user-images.githubusercontent.com/8158673/101086733-2514f980-3566-11eb-862d-e86afdb7ca14.png">
5. join the open source legion!
    <img width="691" alt="image" src="https://user-images.githubusercontent.com/8158673/101086809-40800480-3566-11eb-9e9b-573eff6c7553.png">

**Comment by BillmanH** [comment]
closing this super old issue :)
